name: codeforecon
channels:
  - conda-forge
  - defaults
  - fastai
dependencies:
  - jupyter
  - numpy
  - pandas
  - pip
  - python=3.8
  - pyyaml
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - yaml
  - pycodestyle
  - pyarrow
  - geopandas
  - autopep8
  - geoplot
  - nltk
  - arrow
  - osmnx
  - pandas-datareader
  - pandasdmx
  - pdfminer.six
  - jupyter-book
  - pytest
  - rich
  - pyinstrument
  - loguru
  - pre-commit
  - dataprep
  - pandera
  - linearmodels
  - sympy
  - pingouin
  - jax
  - plotly
  - spacy
  - pandas-profiling
  - plotnine
  - altair
  - datatable
  - cerberus
  - great_expectations
  - dagster
  - icecream
  - waterfallcharts
  - matplotlib-venn
  - pywaffle
  - joypy
  - jupyterlab
  - textstat
  - nbstripout
  - vega_datasets
  - ghp-import
  - colorcet
  - holoviews
  - requests-cache
  - pip:
    - specification_curve
    - twopiece
    - stargazer
    - matplotlib-scalebar
    - black-nb
    - pyhdfe
    - skimpy
